name: Build Linux
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
    - run: |
        sudo apt update
        sudo apt install -y p7zip erofs-utils systemd-container
        aria2c --seed-time=0 https://torrent.fedoraproject.org/torrents/Fedora-KDE-Desktop-Live-x86_64-44.torrent
        mv Fedora-KDE-Desktop-Live-x86_64-44/*.iso .
    - run: bash build.sh
    - uses: actions/upload-artifact@main
      with:
        path: Fedoraemon.iso
        archive: false